
services:
  db:
    image: jpcc141999/db_jenkis:${LATEST_TAG_DB}
    restart: always
    networks:
      - dnet
    volumes:
      - /home/data:/var/lib/postgresql/data


  back:
    image: jpcc141999/back_jenkis:${LATEST_TAG_BACK}
    restart: always
    networks:
      - dnet
    environment:
      - DB_HOST=db
    expose:
      - "8000"
    depends_on:
      - db
 

  nginx:
    image: jpcc141999/front_jenkis:${LATEST_TAG_FRONT}
    restart: always
    networks:
      - dnet
    volumes:
    # en este volumen debes pasar la ruta del servidor host, ya que jenkis le esta pasando la ruta del contenedor de jenkis y ese es el problema
      - /jenkins-data/workspace/test job/Docker-_container_run/nginx.conf:/etc/nginx/conf.d/default.conf
    #por ejemplo si pones solo .nginx.conf, osea haciedno referencia del archivo que esta es el mismo directorio donde esta el yml file, no se va a poder, ya que jenkis fue montado,
    #para tomar los recursos del servidor padre osea la maquina host (ec2 de amazon, o tu maquina local), asi que cuando vayas a compartor un documento es documento esta en el workspace
    #del ael servidor padre
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=pablodevops.com,www.pablodevops.com
      - LETSENCRYPT_HOST=pablodevops.com,www.pablodevops.com  # Dominios para Let's Encrypt
      - LETSENCRYPT_EMAIL=jpcc141999@gmail.com  # Tu correo para Let's Encrypt (importante para la gestión del SSL)
    depends_on:
      - back


  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d  # Montar la configuración de vhost
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - dnet
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - nginx-proxy
    volumes:
      - /run/docker.sock:/var/run/docker.sock:ro  # El mismo docker.sock que en nginx-proxy
      - ./nginx/certs:/etc/nginx/certs  # Compartir certificados SSL entre los contenedores
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy  # Nombre del contenedor nginx-proxy para Let’s Encrypt
    networks:
      - dnet


networks:
  dnet:
    driver: bridge
  
